### ISSUE TITLE
DEMO1 Multiple Events Issue

### ISSUE THREAD

**Issue by Rhapsod** [codrops/Calendario#34]
It seems DEMO1 can only support 3 events shown on a single day?

Can we add a "more" link to pop a small window for showing the rest of the events?

**Comment by deviprsd21** [comment]
DEMO 1 can support only 3 events please elaborate

**Comment by Rhapsod** [comment]
Thanks for the nice calendar. I mean a small issue:
when viewing from a desktop (width > 880px), one grid cannot show too many events (the height of the grid won't extend, so maximum 3 events for my view). I have to use a popup window to show all of them : )

**Comment by deviprsd21** [comment]
Gotcha
