### ISSUE TITLE
Event showing up a day later on Calendar

### ISSUE THREAD

**Issue by sudiptadas** [codrops/Calendario#38]
We are using Calendario in our website but the issue is that the event shows up on the next day. If we pass the caldata as

'05-01-2015':'My event HTML content'

The event appears on 2nd May, 2015. How to resolve the issue?

**Comment by deviprsd21** [comment]
Which version? and please specify your website!

**Comment by sudiptadas** [comment]
Well, it was an older version of calendario. After using the latest script the issue got resolved.

**Comment by deviprsd21** [comment]
Thought so, anyway thanks for addressing it.
