### ISSUE TITLE
Lots of Questions.

### ISSUE THREAD

**Issue by Primar13** [codrops/Calendario#39]
-Is there anyway I can have this Calendar pull Data from a Google Drive Calendar? 
I have an XML with the Data but where would I input the address?
-Any Way to Add an Event that last 3 Days?
    For Example, a "Vacation" that runs the 5-8th of a Month. 
-Also How do I add Multiple Events on a Single Day. 
-I would also like to Try Multiple Event Categories (Meeting, Events, Special Events) Maybe Represented by different Colors

**Comment by Primar13** [comment]
Also How do I add Multiple Events on a Single Day?

**Comment by deviprsd21** [comment]
@Primar13 we currently don't support calendar extensions. So, calendario can't pull data from Google.
- Dates are customizable to any extent, you can have their duration for 3 days. And can also have multiple events. [Examples](https://github.com/codrops/Calendario/blob/master/js/data.js), Look at the last date. It is both multi event and each has a different duration.
- Event categories are a milestone for version 4. Which is currently being built. Check https://github.com/codrops/Calendario/wiki/Milestones!

**Comment by Primar13** [comment]
Yeah... uh, Its not Working...  I thought It might be that I was running an old version so I redownloaded this version with the Default Data and the only Items that appear in that month are the "Event one" and "Event Two" from the Second to last line. 

No events from the Final line of Code appear. 

http://i.imgur.com/IXoOLON.png

Links in the URL Bar if you need a live view.

**Comment by deviprsd21** [comment]
![proof](https://cloud.githubusercontent.com/assets/3809354/6525401/2e177ed4-c42b-11e4-8ccd-32103a77082f.jpg)

Is this what you are talking about? It's working fine even the links!!! If you clearly see the event one is highlighted and the link can be seen below in the browser!

**Comment by Primar13** [comment]
Seems i may be having some caching issues, that i need to fix.

**Comment by deviprsd21** [comment]
And you might want to hide the `time` tags :smiley:

**Comment by Primar13** [comment]
Which File to Hide them?  CSS or the Events file?

Also...  Is there a way to to tell it to make the cells Taller if there is more than one event in it?  It seems to be cutting off Event info. On my Smaller Monitor, and probably other monitors (1366x768)

On the Timeline Version, What date range is it supposed to show, because on the Earlier version it was always showing 1-31, no matter what reange was shown on the desktop version, and now it shows, whats left of the previous month before showing the current month, which is a little disorientating on the timeline view. My people won't really mind it but if at all possible, I would love for the Timeline version to just show the month in question, and not the leftover days from the month before/after.   It looks great with that for the Desktop version, it just doesn't make a lot of sense on the timeline view.

Also, I am still having the issue, where links are not clickable when looking at today, on the desktop version. My Guess is the shimmery image that marks "Today" is appearing above the texts/links making it unclickalble.

Just cause I think I'm not explaining it well, here is a 1 minute, screencap, https://www.youtube.com/watch?v=SVjE_nh_BMs&feature=youtu.be  Give it about a half hour and it schould upscale to HD.

**Comment by deviprsd21** [comment]
@Primar13 
- Hide the `<time>` tags in css file `custom_1.css`. 
- The events are getting cut-off because there overflow is hidden, otherwise you would get scrollbars in each cell making it look ugly.
- The timeline version shows previous and next month leftovers because the option `fillEmpty` in the js file is set to `true`, set it to `false` but this will also not show the leftovers in the calendar view. Since this is an option that can changed during initialization, so first you can detect if it is a mobile or not then set it its value accordingly.
- Make the today link click-able by adding this line `z-index: -1;` after line number 245 in `custom_1.css`
-

**Comment by Primar13** [comment]
Okay, Everything seems to be working at this Time.

**Comment by vishnuvs60** [comment]
@deviprsd 
My project requires to show the previous and next month week dates along with the current month. How can we achieve that. Please help.
Please find the stackoverflow question I have posted now.
[https://stackoverflow.com/questions/44622986/calendario-to-show-previous-and-next-month-dates](url)

As you shown in your image on the comment 
[https://cloud.githubusercontent.com/assets/3809354/6525401/2e177ed4-c42b-11e4-8ccd-32103a77082f.jpg](url)

**Comment by deviprsd** [comment]
@vishnuvs60 You need to use the latest version which can be found here, [Releases](https://github.com/CalendarioFX/Calendario/releases). Then go through the [Read Me](https://github.com/CalendarioFX/Calendario/blob/master/README.md#how-to-use)
