### ISSUE TITLE
Viewing Month Question

### ISSUE THREAD

**Issue by ethikz** [codrops/Calendario#40]
Is there a way to store the month someone was viewing when they left the page and if they hit the back button it loads the calendar on the month they were previously viewing before or is that going to be some custom code?

**Comment by deviprsd21** [comment]
No there is no such inbuilt way, but you can use cookies to do so. [jQuery Cookie](https://github.com/carhartl/jquery-cookie) would be a great tool for you.
```javascript
cal.gotoMonth($.cookie('month'), $.cookie('year'), callback);
```

**Comment by ethikz** [comment]
Ok thanks!

What about showing previous and next month nav so it just doesn't show current?  Is there something built in?

**Comment by deviprsd21** [comment]
No, but the callback in the code `cal.gotoMonth($.cookie('month'), $.cookie('year'), callback)` should be a function, which should update the navs. This function is called once the update of month or year has been done.

**Comment by ethikz** [comment]
Hmm I'm trying to have a a header nav which has the current month and then on the bottom of the calendar have previous and next month.  It works until I get to the end of the year and then it doesn't update properly

````
     getPrevMonthName : function() {
       return this.options.displayMonthAbbr ? this.transObj.monthabbrs[ (this.month - 1) ] : this.transObj.months[ (this.month - 1) ];
     },

     getNextMonthName : function() {
       return this.options.displayMonthAbbr ? this.transObj.monthabbrs[ (this.month + 1) ] : this.transObj.months[ (this.month + 1) ];
     },
````

**Comment by deviprsd21** [comment]
You have to reset the index to get values from the array
```javascript
getPrevMonthName : function() {
          var month = this.month < 1 ? 11 : this.month - 1;
       return this.options.displayMonthAbbr ? this.transObj.monthabbrs[ month ] : this.transObj.months[ month ];
     },
getNextMonthName : function() {
var month = this.month >= 11 ? 0 : this.month + 1;
       return this.options.displayMonthAbbr ? this.transObj.monthabbrs[month] : this.transObj.months[month];
     }
```

**Comment by ethikz** [comment]
That returns an error

````
Cannot read property '1' of undefined
````

**Comment by deviprsd21** [comment]
That has to changes as well, the year gives you the year of the current month, not the previous or next ones.

**Comment by ethikz** [comment]
Ok thanks so I imagine it would be something similar to this for the check?

````
this.month > 0 ? this.year : --this.year;
````

**Comment by deviprsd21** [comment]
It will definitely taken into suggestion

**Comment by ethikz** [comment]
Great, I have one more question.

I am using this for my previous and next year

````
getPrevYear : function() {
      return this.year = this.month > 0 ? this.year : --this.year;;
    },

    getNextYear : function() {
      return this.year = this.month < 11 ? this.year : ++this.year;;
    },
````

When I am showing the first month of the new year or the last month of the previous year it shows correctly but as soon as I navigate it changes the year to 2 years back or forward and then once I change again it updates it correctly.

Any clue why this would be happening?

**Comment by deviprsd21** [comment]
There was question, you probably must have deleted it, because I'm not able to view it.
```javascript
getPrevYear : function() {
    return this.month == 0 ? this.year - 1 : this.year;
},
getNextYear : function() {
    return this.month == 11 ? this.year + 1 : this.year;
}
```

**Comment by ethikz** [comment]
Oh yea I deleted it because I figured out a solution.

````
getPrevYear : function() {
      var currYear = this.year;
      return (this.month > 0 ? currYear : --currYear);
    },
````


Thank you for your comment, yours looks a lot better :+1:

**Comment by deviprsd21** [comment]
Yeah, sure, thank you. Please close this issue if you are done.
