### ISSUE TITLE
Incorrect month start date in IE/Edge in demo

### ISSUE THREAD

**Issue by juganrising** [codrops/Calendario#71]
When I go to https://tympanus.net/Development/Calendario/ on IE it says that April 1, 2020 starts on Thursday instead of Wednesday. The dates end up being shifted and then it causes other issues in the calendar. However, in Demo 2 it shows April 1st being on Wednesday on IE and Chrome.

I have confirmed that this issue happens in IE11 and Microsoft Edge.

**Comment by deviprsd** [comment]
https://github.com/CalendarioFX/Calendario/releases

**Comment by juganrising** [comment]
For anyone else who encounters this issue, IE rounds differently and if the last day of the week is pushed too far then you end up with an offset. Changing the width: calc(100%/7) to 99%/7 will fix it.
